//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/applications/udpapp/customApp/GeneralMsg.msg.
//

#ifndef __INET_GENERALMSG_M_H
#define __INET_GENERALMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class GeneralMsg;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/udpapp/customApp/GeneralMsg.msg:6</tt> by opp_msgtool.
 * <pre>
 * class GeneralMsg extends FieldsChunk
 * {
 *     int sender;
 *     string payload;
 * }
 * </pre>
 */
class INET_API GeneralMsg : public ::inet::FieldsChunk
{
  protected:
    int sender = 0;
    ::omnetpp::opp_string payload;

  private:
    void copy(const GeneralMsg& other);

  protected:
    bool operator==(const GeneralMsg&) = delete;

  public:
    GeneralMsg();
    GeneralMsg(const GeneralMsg& other);
    virtual ~GeneralMsg();
    GeneralMsg& operator=(const GeneralMsg& other);
    virtual GeneralMsg *dup() const override {return new GeneralMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSender() const;
    virtual void setSender(int sender);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GeneralMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GeneralMsg& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::GeneralMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::GeneralMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_GENERALMSG_M_H

